import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

const sidebars: SidebarsConfig = {
  techDocsSidebar: [
    {
      type: "doc",
      id: "index",
      label: "Overview",
    },
    {
      type: "doc",
      id: "coverage",
      label: "Coverage audit",
    },
    {
      type: "category",
      label: "Contracts",
      items: [
        "contracts/minter",
        "contracts/stability-pool-manager",
        "contracts/stability-pool",
        "contracts/genesis",
        "contracts/bao-factory",
        "contracts/reserve-pool",
        "contracts/zap",
        "contracts/harbor-yield",
        "contracts/harbor-swap",
        {
          type: "category",
          label: "Price Oracles",
          items: [
            "contracts/price-oracle",
            {
              type: "category",
              label: "Mainnet",
              items: [
                "contracts/price-oracles/mainnet",
                {
                  type: "autogenerated",
                  dirName: "contracts/price-oracles/mainnet",
                },
              ],
            },
            {
              type: "category",
              label: "Arbitrum",
              items: [
                "contracts/price-oracles/arbitrum",
                {
                  type: "autogenerated",
                  dirName: "contracts/price-oracles/arbitrum",
                },
              ],
            },
            {
              type: "category",
              label: "Base",
              items: [
                "contracts/price-oracles/base",
                {
                  type: "autogenerated",
                  dirName: "contracts/price-oracles/base",
                },
              ],
            },
            {
              type: "category",
              label: "MegaETH",
              items: [
                "contracts/price-oracles/megaeth",
                {
                  type: "autogenerated",
                  dirName: "contracts/price-oracles/megaeth",
                },
              ],
            },
          ],
        },
        "contracts/fee-receiver",
        "contracts/reward-system",
      ],
    },
    {
      type: "category",
      label: "Markets",
      items: [
        { type: "doc", id: "markets/generic", label: "Generic" },
        {
          type: "category",
          label: "haETH",
          link: { type: "doc", id: "markets/haeth/index" },
          items: [
            { type: "doc", id: "markets/haeth/fxusd", label: "fxUSD" },
          ],
        },
        {
          type: "category",
          label: "haBTC",
          link: { type: "doc", id: "markets/habtc/index" },
          items: [
            { type: "doc", id: "markets/habtc/fxusd", label: "fxUSD" },
            { type: "doc", id: "markets/habtc/steth", label: "stETH" },
          ],
        },
        {
          type: "category",
          label: "haEUR",
          link: { type: "doc", id: "markets/haeur/index" },
          items: [
            { type: "doc", id: "markets/haeur/fxusd", label: "fxUSD" },
            { type: "doc", id: "markets/haeur/steth", label: "stETH" },
          ],
        },
        {
          type: "category",
          label: "haGOLD",
          link: { type: "doc", id: "markets/hagold/index" },
          items: [
            { type: "doc", id: "markets/hagold/fxusd", label: "fxUSD" },
            { type: "doc", id: "markets/hagold/steth", label: "stETH" },
          ],
        },
        {
          type: "category",
          label: "haSILVER",
          link: { type: "doc", id: "markets/hasilver/index" },
          items: [
            { type: "doc", id: "markets/hasilver/fxusd", label: "fxUSD" },
            { type: "doc", id: "markets/hasilver/steth", label: "stETH" },
          ],
        },
        {
          type: "category",
          label: "haMCAP",
          link: { type: "doc", id: "markets/hamcap/index" },
          items: [
            { type: "doc", id: "markets/hamcap/fxusd", label: "fxUSD" },
            { type: "doc", id: "markets/hamcap/steth", label: "stETH" },
          ],
        },
        {
          type: "category",
          label: "haUSD",
          link: { type: "doc", id: "markets/hausd/index" },
          items: [
            { type: "doc", id: "markets/hausd/steth", label: "stETH" },
            { type: "doc", id: "markets/hausd/paxg", label: "PAXG" },
            { type: "doc", id: "markets/hausd/wbtc", label: "wBTC" },
            { type: "doc", id: "markets/hausd/tbtc", label: "tBTC" },
          ],
        },
        {
          type: "category",
          label: "haUSD (MegaETH)",
          link: { type: "doc", id: "markets/hausd-megaeth/index" },
          items: [
            {
              type: "doc",
              id: "markets/hausd-megaeth/steth",
              label: "stETH",
            },
          ],
        },
      ],
    },
    {
      type: "category",
      label: "Process Flows",
      items: [
        "process-flows/contract-architecture",
        "process-flows/minting",
        "process-flows/rebalance",
        "process-flows/stability-pools",
      ],
    },
    {
      type: "category",
      label: "Remediation",
      items: ["remediation/fxusd-eth-sail-rebalance"],
    },
  ],
};

export default sidebars;
