import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

const sidebars: SidebarsConfig = {
  techDocsSidebar: [
    {
      type: "doc",
      id: "index",
      label: "Overview",
    },
    {
      type: "doc",
      id: "coverage",
      label: "Coverage audit",
    },
    {
      type: "category",
      label: "Contracts",
      items: [
        "contracts/minter",
        "contracts/stability-pool-manager",
        "contracts/stability-pool",
        "contracts/genesis",
        "contracts/bao-factory",
        "contracts/reserve-pool",
        "contracts/zap",
        {
          type: "category",
          label: "Price Oracles",
          items: [
            "contracts/price-oracle",
            {
              type: "category",
              label: "Mainnet",
              items: [
                "contracts/price-oracles/mainnet",
                {
                  type: "autogenerated",
                  dirName: "contracts/price-oracles/mainnet",
                },
              ],
            },
            {
              type: "category",
              label: "Arbitrum",
              items: [
                "contracts/price-oracles/arbitrum",
                {
                  type: "autogenerated",
                  dirName: "contracts/price-oracles/arbitrum",
                },
              ],
            },
            {
              type: "category",
              label: "Base",
              items: [
                "contracts/price-oracles/base",
                {
                  type: "autogenerated",
                  dirName: "contracts/price-oracles/base",
                },
              ],
            },
            {
              type: "category",
              label: "MegaETH",
              items: [
                "contracts/price-oracles/megaeth",
                {
                  type: "autogenerated",
                  dirName: "contracts/price-oracles/megaeth",
                },
              ],
            },
          ],
        },
        "contracts/fee-receiver",
        "contracts/reward-system",
      ],
    },
    {
      type: "category",
      label: "Markets",
      items: [
        { type: "doc", id: "markets/generic", label: "Generic" },
        { type: "doc", id: "markets/eth-fxsave", label: "fxUSD/ETH Market" },
        { type: "doc", id: "markets/btc-fxusd", label: "fxUSD/BTC Market" },
        { type: "doc", id: "markets/btc-steth", label: "stETH/BTC Market" },
        { type: "doc", id: "markets/fxusd-eur", label: "fxUSD/EUR Market" },
        { type: "doc", id: "markets/steth-eur", label: "stETH/EUR Market" },
        { type: "doc", id: "markets/fxusd-gold", label: "fxUSD/GOLD Market" },
        { type: "doc", id: "markets/steth-gold", label: "stETH/GOLD Market" },
        { type: "doc", id: "markets/fxusd-silver", label: "fxUSD/SILVER Market" },
        { type: "doc", id: "markets/steth-silver", label: "stETH/SILVER Market" },
        { type: "doc", id: "markets/fxusd-mcap", label: "fxUSD/MCAP Market" },
        { type: "doc", id: "markets/steth-mcap", label: "stETH/MCAP Market" },
        {
          type: "doc",
          id: "markets/steth-usd-megaeth",
          label: "stETH/USD Market (MegaETH)",
        },
      ],
    },
    {
      type: "category",
      label: "Process Flows",
      items: [
        "process-flows/contract-architecture",
        "process-flows/minting",
        "process-flows/rebalance",
        "process-flows/stability-pools",
      ],
    },
    {
      type: "category",
      label: "Remediation",
      items: ["remediation/fxusd-eth-sail-rebalance"],
    },
  ],
};

export default sidebars;
